name: Test Workflow

on:
  push:
    branches:
      - master
    paths:
      - '**.js'
  pull_request:
    paths:
      - '**.js'

jobs:
  test:
    container:
      image: node:20-alpine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm test
