name: Test Workflow

on:
  push:
    branches:
      - master
      - wp-coding-standards
    paths:
      - '**.js'
  pull_request:
    paths:
      - '**.js'

jobs:
  test:
    container:
      image: node:24-alpine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm test
  wp-coding-standards:
    container:
      image: dhi.io/composer:2.9.5-alpine3.22-php8.4-dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: composer global config allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
      - run: composer global require --dev wp-coding-standards/wpcs:"^3.0"
      - run: /tmp/vendor/bin/phpcs -s -q -n .
